language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '8'
before_install:
  - yarn global add codecov
script:
  - yarn run cover
  - codecov
after_success:
  - yarn run travis-deploy-once "yarn run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
