sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g codecov
script:
  - npm run lint
  - npm run lint-docs
  - npm run cover
  - codecov
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
