name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm packages using cache
        uses: bahmutov/npm-install@v1
        with:
          # the IBI Group TSDX fork has some dependency issues
          # that cause yarn install to fail on a ci runner. Disabling
          # concurrency allows installation to complete successfully
          install-command: yarn --frozen-lockfile --network-concurrency 1
      - name: Lint Code
        run: yarn lint
      - name: Lint Docs
        run: yarn lint-docs
      - name: Test Code
        run: yarn jest
      - name: Build Package
        run: yarn build

      # at this point, the build is successful
      - name: Semantic Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
